function Hd = bandpass1718
%BANDPASS1718 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 09-Dec-2022 16:25:05

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 100;  % Sampling Frequency

% Fstop1 = 1.3;   % First Stopband Frequency
% Fpass1 = 1.4;   % First Passband Frequency
% Fpass2 = 1.6;   % Second Passband Frequency
% Fstop2 = 1.7;   % Second Stopband Frequency
Fstop1 = 0.8;   % First Stopband Frequency
Fpass1 = 1;   % First Passband Frequency
Fpass2 = 1.5;   % Second Passband Frequency
Fstop2 = 1.7;   % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
    0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
