function Hd = bandpass1718leastsquares2
%BANDPASS1718LEASTSQUARES2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 13-Dec-2022 20:34:32

% FIR least-squares Bandpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 100;  % Sampling Frequency

N      = 5000;  % Order
Fstop1 = 1.6;   % First Stopband Frequency
Fpass1 = 1.7;   % First Passband Frequency
Fpass2 = 1.8;   % Second Passband Frequency
Fstop2 = 1.9;   % Second Stopband Frequency
Wstop1 = 1;     % First Stopband Weight
Wpass  = 1;     % Passband Weight
Wstop2 = 1;     % Second Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2]);
Hd = dfilt.dffir(b);

% [EOF]
